services:
  protoshock_server:
    build:
      context: .
      args:
        SOCKET_ENV_FILE_CONTENT: ${SOCKET_ENV_FILE_CONTENT}
        WEB_ENV_FILE_CONTENT: ${WEB_ENV_FILE_CONTENT}
        DATABASE_ENV_FILE_CONTENT: ${DATABASE_ENV_FILE_CONTENT}
    restart: no
    container_name: protoshock_server
    ports:
      - "8880:8880"