services:
  protoshock_server:
    # Tells Docker Compose to build the image from the Dockerfile in the current directory
    build: .
    restart: no
    # The name of the container that will be created
    container_name: protoshock_server
    # Restarts the container automatically if it stops
    # restart: unless-stopped
    # Maps port 3000 on the host to port 3000 in the container
    # Change the host port (the first number) if it's already in use on your machine
    ports:
      - "3000:3000"
      - "8880:8880"
    # You can define environment variables here if your application needs them
    # environment:
    #   - NODE_ENV=production
    volumes:
      - ./.socket.production.env:/app/packages/socket/.env.production
      - ./.web.production.env:/app/packages/web/.env.production
      - ./.database.production.env:/app/packages/database/.env.production
      - ./shared/magic.db:/app/shared/magic.db