version: "3.9"
name: ProtoshockServer
services:
  socket:
    container_name: protoshock-socket
    hostname: protoshock-socket
    build:
      context: .
      dockerfile: Dockerfile.socket
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: protoshock-socket:latest
    environment:
      NODE_ENV: production
      PORT: 8880
      DATABASE_PATH: /app/shared/magic.db
  MIGRATION_OWNER: "true"
  DB_READY_SENTINEL: /app/shared/.db_ready
      # Example additional envs; user can extend
      SERVER_NAME: "ProtoShock Docker Socket"
      ENABLE_SERVER_ICON: "true"
      SERVER_ICON_FILE: "serverIcon.png"
      ENABLE_SOCKET_ADMIN_UI: "false"
      COUNTRY_CODE: "DK"
      ENABLE_WEB_CLIENT: "true"
      DISABLE_GRACEFUL_SHUTDOWN: "false"
      DEBUG_TYPE: "0"
      SERVER_DESCRIPTION: "meow bruv"
    volumes:
      - shared-data:/app/shared
    ports:
      - "8880:8880"
    depends_on: []
    restart: unless-stopped

  web:
    container_name: protoshock-web
    hostname: protoshock-web
    build:
      context: .
      dockerfile: Dockerfile.web
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    image: protoshock-web:latest
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      SOCKET_SERVER_URL: http://socket:8880
      SOCKET_SERVER_INTERNAL_URL: http://socket:8880
      NEXT_PUBLIC_SOCKET_SERVER_URL: http://socket
      NEXT_PUBLIC_SOCKET_SERVER_PORT: 8880
      NEXT_PUBLIC_APP_PORT: 3000
      DATABASE_PATH: /app/shared/magic.db
  MIGRATION_OWNER: "false"
  DB_READY_SENTINEL: /app/shared/.db_ready
    volumes:
      - shared-data:/app/shared
    ports:
      - "3000:3000"
    depends_on:
      - socket
    restart: unless-stopped

volumes:
  shared-data:
    driver: local
